# Generated by Django 6.0 on 2026-02-07 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPersona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('personality_type', models.CharField(blank=True, max_length=64)),
                ('system_prompt', models.TextField(blank=True)),
                ('voice_config', models.JSONField(blank=True, default=dict)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_personas',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(default='bluesky', max_length=32)),
                ('content', models.TextField()),
                ('status', models.CharField(default='draft', max_length=32)),
                ('engagement_metrics', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='content.aipersona')),
            ],
            options={
                'db_table': 'social_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
