# Generated by Django 6.0 on 2026-02-07 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=64)),
                ('insight_type', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_insights',
                'ordering': ['-generated_at'],
            },
        ),
    ]
