# Generated by Django 6.0 on 2026-02-07 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('watchlist', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=64)),
                ('direction', models.CharField(blank=True, max_length=16)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('pnl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_mock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='behavior.userprofile')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-opened_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trading_date', models.DateField()),
                ('total_trades', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('loss_count', models.IntegerField(default=0)),
                ('avg_hold_time', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('emotional_state', models.CharField(blank=True, max_length=64)),
                ('pattern_flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_metrics', to='behavior.userprofile')),
            ],
            options={
                'db_table': 'behavioral_metrics',
                'ordering': ['-trading_date'],
                'unique_together': {('user', 'trading_date')},
            },
        ),
    ]
